workspace:
  base: /go
  path: src/github.com/jamesk/apidoc-proto/

pipeline:
  vendor-sync:
    image: gtoet/govendor:1.0
    commands: 
      - pwd
      - ls
      - echo ${DRONE_REPO}
      - govendor sync

  build:
    image: gtoet/govendor:1.0
    commands: 
      - go build