workspace:
  base: /go
  path: src/github.com/jamesk/apidoc-proto/

pipeline:
  debug-cmd:
    image: gtoet/govendor:1.0
    commands:
      - ls

  vendor-sync:
    image: gtoet/govendor:1.0
    commands:
      - govendor sync

  build:
    image: gtoet/govendor:1.0
    commands: 
      - go build